### ISSUE TITLE
Show drop-down for data entry / select list fields

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis-ui#1088]
From recent feedback on TP1:
User: I probably missed the discussion but why don't we list the available stored procedures and let the user pick one instead of making the user enter the stored procedure name?

Dev response (my paraphrase): We have a plain input box (<input type="text">) with the autocomplete attribute set to "on" and list attribute prepopulated by dynamic metadata.  However, browsers interpret this setting differently: Chrome shows a down arrow to indicate a list of options is available; Firefox does not.

UX input and the reason for this ticket -- While double-clicking or using the down arrow keyboard key are workarounds to showing the drop-down list, there should be a standard way to show that the list is available, *regardless* of the browser.

There are some related tickets identified by Zoran:
[1] https://github.com/syndesisio/syndesis-ux/issues/40
[2] https://github.com/syndesisio/syndesis-ui/issues/1054
[3] https://github.com/syndesisio/syndesis-rest/issues/599

**Comment by gashcrumb** [comment]
Yeah, we should maybe standardize on a proper select-style input widget instead of leaving it up to the browser to figure out.

**Comment by zregvart** [comment]
I'm looking into how this can be done and with it solve syndesisio/syndesis-rest#599 and https://github.com/syndesisio/syndesis-verifier/issues/45 to boot, right now I have formModel with DynamicSelectModel and the values present but due to syndesisio/syndesis-rest#599 when the user goes back a step on action property definition all values from the pull down are lost.

Also doesn't look good, as I prioritize functionality. Would like to make it look like https://www.patternfly.org/pattern-library/widgets/#bootstrap-select.

**Comment by gashcrumb** [comment]
I think this one would be better -> https://www.patternfly.org/pattern-library/widgets/#bootstrap-combobox

it's similar to a select but allows typing, so kinda combines both features.  We could just use a select control too, but I think we're generally going to have lots of values, the combobox works nicer for this kind of situation.
