### ISSUE TITLE
move the entity stores inside the entity folders?

### ISSUE THREAD

**Issue by jstrachan** [syndesisio/syndesis-ui#110]
to make things a little more modular I wonder if we should move, say, `app/store/integration` inside the `app/integrations` module. So that within `app/integrations` there's all the integration specific code rather than splitting integration related stuff across different trees? We can keep generic store code in `app/store` though.

e.g. to make the function stuff optional and modular it'd be nice if there was just an optional `app/function' tree - whereas right now its split across 2 folders.

**Comment by jimmidyson** [comment]
Stores are decoupled from components & used in multiple places so this affects lazy loading. We don't necessarily want to load the functional area module just to use the store.

**Comment by jstrachan** [comment]
I just find it painful working on a kind, say, 'foo' and have to keep going up and down trees to work on the model / store / view/edit stuff for 'foo' - when it could all be in the same folder.

```
foo/
  store/  
     foo-model 
     foo-service
     foo-store
  view/
  view-page/
  ...
   edit/
  editpage/
```
etc. 

Am sure we could come up with a tree structure that doesn't affect lazy loading but keeps related things together. This is only gonna get more complex as the number of modules increases. e.g. imagine adding the 300 resources from kubernetes into a project as well

**Comment by kahboom** [comment]
I _think_ agree with @jstrachan on this; as the modular structure would mean that if we were to remove a model completely, we should be able to delete a single directory and references to it, instead of having to hunt down where model-related services or pipes would be located.

I think they are two different approaches:
1. "Feature"-based per [Angular style guidelines](https://angular.io/styleguide#04-06) (ie a directory for each "feature" which would contain services, pipes, components, model definitions, etc. specific to a "feature" or, in my opinion, a model, like "connections")
2. Functionality-based (ie a directory for all services, all model definitions, all pipes, all components, all templates, etc.). I think the first one is what we have now and is most like the Angular style guidelines.

Having said that, we do have a "shared" directory (possible [feature component](https://angular.io/styleguide#04-10)?) and can maybe incorporate a "core" module, as suggested [here](https://angular.io/styleguide#04-11). That might be a good way to have a store component that dynamically accepts the model name as a string (although this maybe too abstracted?).

**Comment by gashcrumb** [comment]
It's definitely more painful for development but lazy loading support trumps our convenience, needs to be a separate module.
