### ISSUE TITLE
Add integration Import/Export buttons

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-ui#1160]
Integration details view should have an export button.
Integration list should have an import button.
They should use the APIs created with https://github.com/syndesisio/syndesis-rest/issues/764 to download a .zip file which then you pick to import.

**Comment by gashcrumb** [comment]
I guess for the list page it'd probably make sense to have an `Export...` entry in the pop-up menu rather than a button, you'd add it in here -> https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/list/list.component.ts#L78-L109 and then add another case in this function -> https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/components/integrationViewBase.component.ts#L39

**Comment by gashcrumb** [comment]
For an `Import...` button on the list page it should be a matter of adding it here -> https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/list-page/list-page.component.html#L7-L11
