### ISSUE TITLE
Bookmarking / Refreshing Data Mapper results in empty page with non-functional menu.

### ISSUE THREAD

**Issue by jbakermd** [syndesisio/syndesis-ui#428]
When I edit an integration in the Data Mapper UI within iPAAS, I'm led to this page:

http://localhost:4200/integrations/edit/1/step-configure/2

If I refresh this page or open it fresh, I'm presented with an iPAAS screen that doesn't show the DataMapper UI, and the Menu on the top left of the page doesn't work if I click on "Integrations". 

There are two issues here:

a) The DataMapper UI isn't showing up in this reload scenario.

b) The menu seems to be non-functional in this reload scenario.

**Comment by jbakermd** [comment]
Btw. If I hard-refresh (shift+f5 or shift+reload-button in chrome), I'm taken back to the iPAAS root page and the menu is functional again.

**Comment by gashcrumb** [comment]
Yeah, looks like there's an error that's occurring now in the JS console as the page is loading, likely because some of the view is initializing before the integration is loaded.  Will look into this, as it's super-annoying :-)

In some cases we don't maintain the state necessary to re-create views, but at least you should wind up at the 'save or add step' page, checking that now though that doesn't seem to be happening.

**Comment by jbakermd** [comment]
Ok, lmk if you need a change in data mapper to delay initialization in some way. You *should* be able to delay it by calling the initializationservice.initialize() method later, but if that doesn't work, lmk what'd help. @gashcrumb

**Comment by gashcrumb** [comment]
Tweaked the template to avoid the NPE first off in the linked PR.  It would be nice to be able to refresh and kinda stay on the same view if it's in the integration, I'll see if I can make that a bit better tomorrow.

**Comment by gashcrumb** [comment]
It's possible now to refresh and have the page kinda stay where expected, changes to how the integration is loaded and the editor is initialized fixes this one I think.
