### ISSUE TITLE
No "Publish" when re-editing Draft integration

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#530]
When an integation was "Save as Draft" and then edited again, starting from the integration list by clicking on it, then there is no "Publish" button anymore although the integration is ready to publish

![image](https://cloud.githubusercontent.com/assets/99080/25498128/2fecb9d4-2b87-11e7-9d25-15fa65a85497.png)

![image](https://cloud.githubusercontent.com/assets/99080/25498169/4f3ebb16-2b87-11e7-984b-da1ff9348655.png)

**Comment by gashcrumb** [comment]
Ah, I think it's because those two separate buttons are on the 'name' page, not on this save or publish page...  Maybe both buttons should just be on both pages, the purpose of the 'Save' button on this page currently is to punt you to name the integration if it hasn't been done yet, but if that's been completed then it just saves the integration.

**Comment by rhuss** [comment]
For me, it makes sense to include both buttons. I'm not a big fan of appearing and disappearing buttons (but prefer activated and deactivated buttons which are always there). But I'm no UX expert either ;-)

**Comment by gashcrumb** [comment]
This is fixed btw...
