### ISSUE TITLE
Kebab menu should be consistend on dashboard and integrations list

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#579]
![screenshot_20170613_171857](https://user-images.githubusercontent.com/8707241/27090149-b03dc368-505c-11e7-9350-1429f028ccfc.png)
![screenshot_20170613_171928](https://user-images.githubusercontent.com/8707241/27090150-b03df432-505c-11e7-829f-60ba068fb64e.png)

**Comment by gashcrumb** [comment]
Agreed, that menu should probably be refactored into it's own controller so the same actions are consistently handled across views.

**Comment by dongniwang** [comment]
@gashcrumb @jludvice: I think we had this conversation before, the integration list on dashboard has its own set of actions because the list is showing Top 5 integrations. And if we have the same set of actions from the actual integration list page, things may get complicated as I believe we have a "duplicate" action there. I don't think we should have a "duplicate" action on the dashboard integration list.

**Comment by kahboom** [comment]
@dongniwang Hey! Totally agree, however, we can still refactor without requiring the list of contents to be the same, but to just use the template and logic in both places.

**Comment by jludvice** [comment]
I probably missed the original discussion @dongniwang, sorry.

Anyway, we could "hide" some actions from dashboard integration kebab menu,
but imho it's not good idea to have this option available just on dashboard and not on integrations list page.

How many action items we expect in this kebab menu?
Is there really a need to hide something on dashboard if it's 2 or 3 items like `Edit` and `Delete`?

As a user I'd actually expect the consistent set of actions across all places where I can access this menu.

**Comment by dongniwang** [comment]
No worries! I probably miscommunicated something on my previous comment. 

I don't mean to hide all the action, and I agree that Edit and Delete should be available on dashboard. The only action which probably doesn't make sense is the Duplicate action on dashboard. If you duplicate an integration, this NEW integration would not be one of the top 5 integrations since it has just been created. 

We can probably keep Duplicate action on dashboard but just make it unavailable. The other way is to make a smooth transition from dashboard to integration list when users duplicate any integrations from dashboard. 

@jludvice @gashcrumb @kahboom

**Comment by gashcrumb** [comment]
@akieling So currently I don't think we even support 'duplicate' currently so let's use the same menu if possible, we can always hide duplicate if necessary going forward.
