### ISSUE TITLE
Refactor FormFactoryService

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#598]
Refactor the FormFactoryService for the following:
- It should be able to handle form-generation independently of [ng2-dynamic-forms](https://github.com/udos86/ng2-dynamic-forms).
- More importantly, it should support the wide array of features offered by ng2-dynamic-forms, not just passing in elements field-by-field which are provided by the API. For instance, the ability to define a `DynamicFormGroupModel` and `DynamicFormArrayModel ` are quite important for more complex forms.
- Most importantly, we need to document this service.

**Comment by gashcrumb** [comment]
Only thing, if you want to generate a form you can certainly just use ng2-dynamic-forms directly.  This forms service is really only a glue layer that transforms the existing camel component JSON into the config/API calls to create an ng2-dynamic-forms instance.  The intent isn't really to provide an interface to ng2-dynamic-forms, just a translation layer to handle most simple cases where a connection/component has some inputs needed for an action.

For more complicated cases where we basically have a custom UI provided by UXD I would expect that generally we'd be creating a new component to implement that UI rather than try and handle it in this forms service.  So I'm not sure this bug really needs to be open, might be better to raise specific issues as required.

**Comment by kahboom** [comment]
@gashcrumb - I guess the question to be asked here is, do you want the form service to support groups and arrays -- would that be possible to map with Camel component JSON? It would certainly make our lives easier if that were possible, and if we wanted that, at which point I'd say we need to do some refactoring. I don't consider this a bug, just a refactoring task if we did want it to support those features.

**Comment by kahboom** [comment]
@gashcrumb - Perhaps it's worth evaluating whether or not we should be using ng2-dynamic-forms? Do you think rolling our own might allow for more fine-grained control? The reason I say this is because our needs, especially pertaining to forms, are not the simplest and I don't foresee them getting any simpler.

**Comment by gashcrumb** [comment]
Seems like a lot of work, what's would be the benefit?  We now have our own UI layer for ng2-dynamic-forms which allows us to tweak the forms however we want.  It's got documentation, examples, API documentation, supports arrays of things, and support for more controls than we're currently using.

**Comment by kahboom** [comment]
>We now have our own UI layer for ng2-dynamic-forms which allows us to tweak the forms however we want. It's got documentation, examples, API documentation, supports arrays of things, and support for more controls than we're currently using.

At the risk of sounding stupid, can you point me to this UI layer? Do you mean this FormFactoryService that I was saying we should refactor?

**Comment by gashcrumb** [comment]
This bit that @riccardo-forina contributed -> https://github.com/syndesisio/syndesis-ui/tree/master/src/app/common/ui-patternfly
