### ISSUE TITLE
Cannot add additional filter step

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#631]
@rhuss commented on [Fri Jul 21 2017](https://github.com/syndesisio/syndesis-rest/issues/452)

When pussing "+ Add another rule" the following JavaScript exception occurs. This happens when creating a new filter step or editing an already existing filter step

![image](https://user-images.githubusercontent.com/99080/28450858-49ceacf4-6dea-11e7-8676-c7e33f72215f.png)

**Comment by kahboom** [comment]
@rhuss - Can you still reproduce this?

**Comment by kahboom** [comment]
Update: I'm able to reproduce on staging, but not locally. Looking into this.

**Comment by rhuss** [comment]
I can reproduce it on staging and locally with the latest changes from master.

**Comment by kahboom** [comment]
Can confirm this is an AOT compiling issue with ng2-dynamic-forms, causing a runtime exception. Will try excluding this function causing the error from mangling and see how that works out. Wish me luck...

**Comment by kahboom** [comment]
The `findById` method provided by ng2-dynamic-forms does not appear to work with AOT. I tried the following alternative of directly accessing the object in the array, rather than traversing the DOM with an element selector, which seems to have worked, but does there is some hacking to be done, as it still does not work and renders a different type of error. And this is why I hate working with too many third party JS libraries: 😂

<img width="1031" alt="screenshot 2017-07-28 21 55 53" src="https://user-images.githubusercontent.com/3844502/28741276-c048f0f0-73e0-11e7-855c-9b3312681ded.png">
<img width="1303" alt="screenshot 2017-07-28 21 56 24" src="https://user-images.githubusercontent.com/3844502/28741278-c390c2d8-73e0-11e7-9894-b9ccce1c7dc1.png">
<img width="1309" alt="screenshot 2017-07-28 21 56 38" src="https://user-images.githubusercontent.com/3844502/28741279-c5d29f12-73e0-11e7-87e3-010bc86f5b46.png">

**Comment by kahboom** [comment]
@gashcrumb - This has been a blocker for a while (my fault), but I'm wasting too much time on it and need to move forward. I've been working on other issues simultaneously, but this is slowing me to a crawl and seems very straightforward. If you could take a look, I would really appreciate it.

I have opened up an issue with the ng2-dynamic-forms lib here: https://github.com/udos86/ng2-dynamic-forms/issues/458

Btw, getting the following AOT transpilation errors as of the latest pull (only on AOT):

<img width="932" alt="screenshot 2017-07-31 19 15 53" src="https://user-images.githubusercontent.com/3844502/28803580-9d849a7c-762b-11e7-9a39-10e231a4df6d.png">

Shouldn't we be avoiding referencing jQuery completely from components, or is that less important in Angular than in AngularJS now? Maybe binding it to an Angular model like the old way.

**Comment by gashcrumb** [comment]
@kahboom I don't get the AOT compile error here.  Have you run `yarn install` and restarted your build after pulling?

**Comment by gashcrumb** [comment]
Have a lead on a fix for this...

**Comment by kahboom** [comment]
@gashcrumb were you able to reproduce the error later on? I was thinking that a quick workaround would be to just leave the 'add' button in each rule group for now and come back to this. Wdyt?
