### ISSUE TITLE
No 'cancel' when adding a connection to an integration 

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#754]
When adding a (third) connection to an integration, there is no way to cancel this step:

![image](https://user-images.githubusercontent.com/99080/29128391-f7ff6ca8-7d23-11e7-8ab8-3aa25174ac96.png)

**Comment by gashcrumb** [comment]
This kind of relates to https://github.com/syndesisio/syndesis-ui/issues/251

we used to have a "back" button, but turned out to be very confusing, and actually exposed lots of horrid edge cases.  With some of the tightening up in the editor I think having a cancel button available when going through a flow of pages that then goes and removes the "new" step/connection the user is adding would make sense.

**Comment by dongniwang** [comment]
Feels like it might be a good idea to revisit the button issues and document all the design decisions somewhere in the ux repo?

**Comment by gashcrumb** [comment]
yeah, definitely, otherwise these decisions get lost...
