### ISSUE TITLE
Refactoring: remove connections/view/view.component.*

### ISSUE THREAD

**Issue by akieling** [syndesisio/syndesis-ui#907]
I'd like to suggest removing the ConnectionViewComponent and move the templates and logic to each create-page sub-component (connection-details, configure-fields, and review). I find confusing having some stuff in the step components and some stuff in the view component.
@gashcrumb @kahboom @astefanutti please let me know what you think.

**Comment by gashcrumb** [comment]
+1

On Sep 6, 2017 5:08 PM, "Alexandre Kieling" <notifications@github.com>
wrote:

I'd like to suggest removing the ConnectionViewComponent and move the
templates and logic to each create-page sub-component (connection-details,
configure-fields, and review).
@gashcrumb <https://github.com/gashcrumb> @kahboom
<https://github.com/kahboom> @astefanutti <https://github.com/astefanutti>
please let me know what you think.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/syndesis-ui/issues/907>, or mute the thread
